# Generated by Django 4.2.5 on 2023-10-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_desciprtion_listing_sold_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
